//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShawarmaRecipe
    {
        public int ShawarmaRecipeID { get; set; }
        public int ShawarmaID { get; set; }
        public int IngredientID { get; set; }
        public int Weight { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Shawarma Shawarma { get; set; }
    }
}
