//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task1ConsoleLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceController
    {
        public int PriceControllerID { get; set; }
        public int ShawarmaID { get; set; }
        public decimal Price { get; set; }
        public int SellingPointID { get; set; }
        public string Comment { get; set; }
    
        public virtual Shawarma Shawarma { get; set; }
        public virtual SellingPoint SellingPoint { get; set; }
    }
}
